networks:
  go_restful_api:
    name: go_restful_api
    driver: bridge

services:
  server:
    image: golang:1.22.5-bullseye
    container_name: server-con
    build: .
    hostname: server
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    networks:
      - go_restful_api
    depends_on:
      - db

  pgadmin:
    image: ${PGADMIN_IMAGE:-dpage/pgadmin4:latest}
    container_name: pgadmin-con
    hostname: pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@jb.dev}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-jb12345}

  postgres:
    image: postgres:13-alpine3.20
    container_name: potgres-con
    hostname: postgres
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${PGADMIN_PORT:-5432}
      - POSTGRES_PASSWORD=${PGADMIN_PORT:-p@ssword1234}
      - POSTGRES_DB=${POSTGRES_DB:-init}
    networks:
      - go_restful_api

volumes:
  postgres_data: